### PR TITLE
Utilize `git config`

### PR DESCRIPTION
**Pull request by drewbug**
This will let me put `git-author-rewrite.sh` to rest.

### CODE REVIEW

**Comment by hnrysmth** [comment]
This works great, thanks! I've never liked the ugly commit author ppl generated.

I'm gonna merge it and see if I can improve it any. Like maybe Rugged provides an API to get the config without having to use the backticks. If not I'll get a release out before bed :smile:

**Comment by drewbug** [comment]
Thanks! Yeah, perhaps `Rugged::Config.global` would be useful?

**Comment by hnrysmth** [comment]
Yep pretty much that. Spent a moment stopping it from choking when there's no ~/.gitconfig and the finished code looks like this

```ruby
begin
  git_config = Rugged::Config.open_global.to_hash
rescue Rugged::OSError
  git_config = {}
end

author = {
  :email => git_config.fetch('user.email', "#{ENV['USER']}@#{Socket.gethostname}"),
  :time  => Time.now,
  :name  => git_config.fetch('user.name', ENV['USER']),
}
```

Just running through the release checklist now!

**Comment by drewbug** [comment]
Awesome! Thanks!

**Comment by hnrysmth** [comment]
It's done! If you run `gem update ppl` it should update to `2.4.0` and no more nasty shell script :smile:

**Pull request merged**
